name: Deploy
on:
  push:
    branches:
      - master

permissions:
  actions: write
  contents: read

jobs:
  deploy-prod:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start the app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /fund-her-health &&
            npm run dev
